# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
 # webAppName: 'ServiceNow'
  #serviceConnection: '<Name of your webARM Service connection>'
  azureSubscriptionId: 'c2737fa4-a93d-45ad-9dd7-afc03b66b548'
  loadTestResource: 'ServiceNow_Azure-Load'
  loadTestResourceGroup: '365d652b-7981-4aff-95f5-1ef85206d4a8'
  location: 'North Europe'


stages:
- stage: LoadTest
    - task: AzureLoadTest@1
      inputs:
        azureSubscription: $(serviceConnection)
        loadTestConfigFile: 'SampleApp.yaml'
        resourceGroup: $(loadTestResourceGroup)
        loadTestResource: $(loadTestResource)
        env: |
          [
            {
            "name": "webapp",
            "value": "$(webAppName).azurewebsites.net"
            }
          ]
          
    - publish: $(System.DefaultWorkingDirectory)/loadTest
      artifact: results
